export const homeConstants = {
  FETCH_TOP_GAMES_INIT: 'FETCH_TOP_GAMES_INIT',
  FETCH_TOP_GAMES_SUCCESS: 'FETCH_TOP_GAMES_SUCCESS',
  FETCH_TOP_GAMES_ERROR: 'FETCH_TOP_GAMES_ERROR',

  FETCH_NEW_GAMES_INIT: 'FETCH_NEW_GAMES_INIT',
  FETCH_NEW_GAMES_SUCCESS: 'FETCH_NEW_GAMES_SUCCESS',
  FETCH_NEW_GAMES_ERROR: 'FETCH_NEW_GAMES_ERROR',
}
